---
- name: Copy and Install XDR agent on Linux Hosts
  hosts: linux_hosts
  remote_user: ec2-user
  become: true
  tasks:
    - name: Download cortex file from nexus
      get_url:
        url: "{{ nexus_url }}"
        dest: "{{ remote_dir }}/{{ nexus_file }}"
        username: "{{ nexus_user }}"
        password: "{{ nexus_password }}"
        force: true

    - name: copy and run script to install cortex on EC2 Linux
      script: ./install_Cortex_Linux.sh
    
    - name: copy and run script to install defender on EC2 Linux
      script: ./install_defender_linux.sh
