- name: SSH to remote server with credentials
  hosts: all
  remote_user: "{{ user }}"
  vars:
    ansible_ssh_pass: "{{ pass }}"

  tasks:
    - name: Download file from Nexus
      win_get_url:
        url: http://10.1.30.3:8081/repository/cortex/cortex/Cortex_win_x64.msi
        dest: "C:\Users\"
        username: "{{ nexus_user }}"
        password: "{{ nexus_password }}"
        force: true
        
    - name: copy script install cortex to target hosts
      win_copy:
        src: ./Install_Cortex_Window.ps1
        dest: C:\Users\
    
    - name: run script install cortex on target hosts
      win_shell: C:\Users\Install_Cortex_Window.ps1


