- name: SSH to remote server with credentials
  hosts: all
  remote_user: "{{ user }}"
  vars:
    ansible_ssh_pass: "{{ pass }}"

  tasks:
    - name: Copy File
      win_copy:
        src: C:\test.txt
        dest: C:\Users\
        remote_src: yes